apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: np06c7xw2-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/np06c7xw2-java-quarkus-gitops